<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
#ex 1
A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

#ex2
#A  = [[1, 2], [3, 4]]
#B  = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

#ex3
#A = [[1, 2], [3, 4]]
#B = [[1, 4], [5, 6], [7, 8],[9, 6]]

def get_matrix_dim(matrix):
    ''' Get the given matrix dimensions: rows x columns'''
    rows = len(matrix)
    columns = len(matrix[0])
    print("Given Matrix dimensions (rows X columns):", rows, columns)
    return(rows, columns)

def get_rows(matrix, row):
    '''Return row of given matrix'''
    return matrix[row]

def get_columns(matrix, columns):
    '''Return the column of given matrix'''
    column = [matrix[i][columns] for i in range(len(matrix))]
    return column

def mul_rows_cloumns(row, column):
    '''Return sum of mutipilcation of given row with column'''
    return (sum(row[i]*column[i] for i in range(len(row))))

def matrix_mul(A, B):
    '''Does Matrix Multiplication'''
    (rows_a, columns_a) = get_matrix_dim(A)
    (rows_b, columns_b) = get_matrix_dim(B)
    if (columns_a != rows_b):
        print("Matrix dimensions mis-match...multiplication is not possible")
    else:
        matrix = []
        for i in range(len(A)):
            matrix.append([])
            for j in range(len(B[0])):
                matrix[i].append(mul_rows_cloumns(get_rows(A, i), get_columns(B, j)))
        print("A*B =", matrix)
    return

if __name__ == "__main__":
    matrix_mul(A, B)


Given Matrix dimensions (rows X columns): 3 3
Given Matrix dimensions (rows X columns): 3 3
A*B = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [23]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def pick_a_number_from_list(A):
    '''picking an element from with the probability propotional to its magnitude'''
    weightage_list = []
 
    for ele in A:
        weightage_list.append(ele/sum(A))
    #print(weightage_list)
    cumulative_list = []
    m = 0
    for j in range(0,len(weightage_list)):
        m += weightage_list[j]
        cumulative_list.append(m)
        
    r = uniform(0,1)

    for i in range(len(cumulative_list)):
        if r < cumulative_list[i]:
            return i
    
    return i

def sampling_based_on_magnitued():
    new_list = []
    a = sorted(A)
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        new_list.append(A[number])

    for i in a:
        print("value={0}, Picked={1}".format(i,new_list.count(i)))
        
if __name__ == "__main__":
    sampling_based_on_magnitued()

value=0, Picked=0
value=5, Picked=0
value=6, Picked=0
value=10, Picked=6
value=13, Picked=7
value=27, Picked=7
value=28, Picked=9
value=45, Picked=10
value=79, Picked=27
value=100, Picked=33


<h3> Q3: Replace the digits in the string with </h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with 
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [87]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
string = "#2a$#b%c%561#"
def replace_digits(string):
    '''Replace the digits with # and delete the rest'''
    # write your code
    #step1 : get the digits from given string
    digits = re.findall("[0-9]", string)
    temp_str = "".join(digits)
    #Step 2: replace digits with "#"
    output_str = re.sub("[0-9]", "#", temp_str)
    return(output_str)

if __name__ == "__main__":
    print("Output:", replace_digits(string))


Output: ####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [19]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
import math
students = ['student1', 'student2', 'student3', 'student4', 'student5',\
        'student6', 'student7', 'student8', 'student9', 'student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

def percentile(marks,per):
    n = len(marks)
    p = (per * (n+1)) /100
    #print(p)
    if p.is_integer():
        return sorted(marks)[p-1]
    else:
        l = int(p)-1
        m = int(p)
        x1 = sorted(marks)[l]
        x2 = sorted(marks)[m]
        return((x1+x2)/2)
    
def display_dash_board(students, marks):
    '''Get the required information'''
    #step 1: combined the two lists
    combined_list = zip(students, marks)
    #step 2 : sorted the list based on the marks as ascending order
    combined_ordered_list = sorted(combined_list, key=lambda x: x[1])
    #write code for computing top top 5 students
    #Who got top 5 ranks, in the descending order of marks
    top_5_students = combined_ordered_list[-1:-6:-1]
    #Who got least 5 ranks, in the increasing order of marks
    least_5_students = combined_ordered_list[0:5]
    #Who got marks between >25th percentile <75th percentile, in the increasing order of marks
    lower_25th_percentile_limit = percentile(marks, 25)
    higher_75th_percentile_limit = percentile(marks, 75)
    #print(lower_25th_percentile_limit,higher_75th_percentile_limit)
    students_within_25_and_75 = [x for x in combined_ordered_list
                if x[1] >= lower_25th_percentile_limit and x[1] < higher_75th_percentile_limit]
    del combined_list
    del combined_ordered_list
    return top_5_students, least_5_students, students_within_25_and_75

if __name__ == "__main__":
    top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
    print("Top 5 ranks, in the descending order of marks")
    print(*top_5_students, sep="\n")
    print("Least 5 ranks, in the increasing order of marks")
    print(*least_5_students, sep="\n")
    print("Marks between >25th percentile and <75th percentile, in the increasing order of marks")
    print(*students_within_25_and_75, sep="\n")


Top 5 ranks, in the descending order of marks
('student8', 98)
('student10', 80)
('student2', 78)
('student5', 48)
('student7', 47)
Least 5 ranks, in the increasing order of marks
('student3', 12)
('student4', 14)
('student9', 22)
('student6', 43)
('student1', 45)
Marks between >25th percentile and <75th percentile, in the increasing order of marks
('student9', 22)
('student6', 43)
('student1', 45)
('student7', 47)
('student5', 48)
('student2', 78)


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [67]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
# here S is list of tuples and P is a tuple ot len=2
def dot(A,B):
    return (sum(a*b for a,b in zip(A,B)))

def closest_points_to_p(S, P):
    '''find top five closest points given in list -- from given point'''
    # write your code here
    dist = []
    for i in range(len(S)):
        Q = S[i]
        dist.append(1 - (dot(Q, P)/(math.sqrt(dot(Q, Q)) * (math.sqrt(dot(P, P))))))
    closest_points_to_p = zip(S, dist)
    closest_points_to_p = sorted(closest_points_to_p, key=lambda x: x[1])

    closest_five_points_to_p = []
    for i in range(len(closest_points_to_p)):
        if i < 5:
            closest_five_points_to_p.append(closest_points_to_p[i][0])
    return closest_five_points_to_p  # its list of tuples

if __name__ == "__main__":
    S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
    P = (3, -4)
    points = closest_points_to_p(S, P)
    print(*points, sep="\n") #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [53]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    '''points locations w.r.t given line'''
    # your code
    red_points_results = []
    blue_points_results = []
    
    for ele in red:
        equ = line.replace('x','*'+str(ele[0]))
        equ = equ.replace('y','*'+str(ele[1]))
        red_points_results.append(eval(equ))
    #print(red_points_status)
    red_points_status = all(ele >=0 for ele in red_points_results)

    for ele in blue:
        equ = line.replace('x','*'+str(ele[0]))
        equ = equ.replace('y','*'+str(ele[1]))
        blue_points_results.append(eval(equ))
    #print(blue_points_status)
    blue_points_status = all(ele >= 0 for ele in blue_points_results)
    
    #print(red_status,blue_status)
    if (red_points_status != blue_points_status):
        return "YES"
    else:
        return "NO"   

if __name__ == "__main__":
    Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
    Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]
    Lines = ["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

    for i in Lines:
        yes_or_no = i_am_the_one(Red, Blue, i)
        print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [52]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    '''curve smooting - filf the missing with average'''
    input_list = string.split(',')
    data_present_list = []
    
    for i in range(0,len(input_list)):
        if input_list[i] == "_":
            continue
        else:
            data_present_list.append((input_list[i],i))
    
    #addiotnal case
    if input_list[0] == "_":
        data_present_list.insert(0, (str(0),0))
    if input_list[-1] == "_":
        data_present_list.append((str(0),len(input_list)-1))      

    #print(data_present_list)
    l = 0
    while l < (len(data_present_list)-1):
            x1 = data_present_list[l]
            x2 = data_present_list[l+1]
            avg = int(float(x1[0])) + int(float(x2[0]))
            count = x2[1] - x1[1] + 1
            avg = avg/count
            for i in range(x1[1],x2[1]+1):
                input_list[i]=str(avg)
            data_present_list[l+1] = (str(avg),x2[1])
            l = l + 1
                                                                                               
    return input_list

if __name__ == "__main__":
    S =  "_,_,30,_,_,_,50,_,_"
    smoothed_values= curve_smoothing(S)
    results_values = [int(float(x)) for x in smoothed_values]
    print("Input:", S)
    print("Output:")
    print(*results_values, sep=',')

Input: _,_,30,_,_,_,50,_,_
Output:
10,10,12,12,12,12,4,4,4


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [32]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code

# you can free to change all these codes/structure
def conditional_probabilites(A, f, s):
    '''compute conditional probabilites'''
    d = 0
    for i in range(len(A)):
        if A[i][1] == s:
            d += 1
    n = 0
    for i in range(len(A)):
        if A[i][1] == s and A[i][0] == f:
            n += 1
    print("P(F={0}|S=={1})={2}/{3}".format(f, s, n, d))
        
def compute_conditional_probabilites(A):
    '''compute conditional probabilites'''
    F = ['F1', 'F2', 'F3', 'F4', 'F5']
    S = ['S1', 'S2', 'S3']
    for f in F:
        for s in S:
            conditional_probabilites(A, f, s)
        print("\n")
    return
            
if __name__ == "__main__":
    A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], \
         ['F3', 'S2'], ['F2', 'S1'],['F4', 'S1'],['F4', 'S3'],['F5', 'S1']]
    compute_conditional_probabilites(A)

P(F=F1|S==S1)=1/4
P(F=F1|S==S2)=1/3
P(F=F1|S==S3)=0/3


P(F=F2|S==S1)=1/4
P(F=F2|S==S2)=1/3
P(F=F2|S==S3)=1/3


P(F=F3|S==S1)=0/4
P(F=F3|S==S2)=1/3
P(F=F3|S==S3)=1/3


P(F=F4|S==S1)=1/4
P(F=F4|S==S2)=0/3
P(F=F4|S==S3)=1/3


P(F=F5|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F5|S==S3)=0/3




<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    '''Get the required information on given two strings
    Number of common words between S1, S2
    Words in S1 but not in S2
    Words in S2 but not in S1'''
    #init - values
    a = 0
    b = []
    c = []
    # repeat S1 words in S2 compare
    for i in S1.split():
        if i in S2:
            a += 1
        else:
            b.append(i)
            
    #repeat S2 words not in S1 compare        
    for i in S2.split():
        if i not in S1:
            c.append(i)
    
    return a, b, c

if __name__ == "__main__":
    S1 = "the first column F will contain only 5 uniques values"
    S2 = "the second column S will contain only 3 uniques values"
    a, b, c = string_features(S1, S2)
    print("Number of common words between S1, S2 :", a)
    print("Words in S1 but not in S2:", b)
    print("Words in S2 but not in S1:", c)

Number of common words between S1, S2 : 7
Words in S1 but not in S2: ['first', 'F', '5']
Words in S2 but not in S1: ['second', 'S', '3']


<h3> Q10: Error Function</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [3]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    '''Evalue the equation: Compute log loss of given lists of list'''
    loss = 0
    for i in range(len(A)):
        y = A[i][0]
        y_score = A[i][1]
        loss = loss + ((y * math.log10(y_score) + ((1-y) * math.log10(1-y_score))))
        
    loss = -loss/len(A)
    return loss

if __name__ == "__main__":
    A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
    loss = compute_log_loss(A)
    print(loss)

0.42430993457031635
